version: "1"
networks:
  sklkv:
    external: true
    name: sklkv
services:
  backend:
    networks:
      - sklkv
    build: .
    container_name: skolgis-backend
    ports:
      - "5000:5000"
    restart: on-failure
  geoserver:
    image: kartoza/geoserver:2.20.1
    container_name: geoserver
    restart: on-failure
    networks:
      - sklkv
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
    ports:
      - "8081:8080"
    logging:
      options:
        max-size: 10m
    environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir/gwc
      - GEOSERVER_ADMIN_USER=skolkovoroot
      - GEOSERVER_ADMIN_PASSWORD=MEWt4wneYVZy2cPvr3j4
      - INITIAL_MEMORY=1G
      - MAXIMUM_MEMORY=2G
      # убираем ПУСТОЙ HTTP_PROXY_NAME
      # - HTTP_PROXY_NAME=${HTTP_PROXY_NAME}
      # фиксируем внешний базовый URL – этого достаточно
      - PROXY_BASE_URL=http://89.223.68.75/geoserver/
      # (опционально, помогает некоторым сборкам читать PROXY_BASE_URL)
      - JAVA_OPTS=-DALLOW_ENV_PARAMETRIZATION=true
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/geoserver/web/"]
      interval: 40s
      timeout: 10s
      retries: 7
  #nginx:
  #  image: nginx
  #  container_name: skolgis-nginx
  #  restart: on-failure
  #  networks:
  #    - sklkv
  #  volumes:
  #    - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
  #    - ./nginx/locations.conf:/etc/nginx/conf.d/locations/locations.conf
  #  ports:
  #    - "4300:4300"
volumes:
  geoserver_data: {}