import os, re
import requests
from requests.auth import HTTPBasicAuth
from geo.Geoserver import Geoserver, GeoserverException
from xml.etree.ElementTree import Element, SubElement, tostring
from xml.dom import minidom
from typing import Any, Dict, Optional, Tuple
from src.config import Config
from src.utils import get_logger

logger = get_logger(__name__)

geo = Geoserver(Config.GEOSERVER_ROOT, username=Config.GEOSERVER_USER, password=Config.GEOSERVER_PWD)

NS_SLD = "http://www.opengis.net/sld"
NS_OGC = "http://www.opengis.net/ogc"
NS_GML = "http://www.opengis.net/gml"

def publish_on_geoserver(table_name: str):
    """Публикует слой на Geoserver
    """

    sql = 'SELECT * FROM geo.%s' % table_name
    try:
        geo.delete_layer(layer_name=table_name, workspace=Config.GEOSERVER_WORKSPACE)
    except GeoserverException:
        pass
    except Exception as e:
        raise e
    result = geo.publish_featurestore_sqlview(store_name=Config.GEOSERVER_STORE_NAME, name=table_name, 
        sql=sql, workspace=Config.GEOSERVER_WORKSPACE)
    return table_name


def clear_geoserver_cache(name: str):
    """Очищает кэш слоя на geoserver
    """
    url = f"{Config.GEOSERVER_ROOT}/gwc/rest/seed/skolkovo_layers:{name}" #.json
    print(url, Config.GEOSERVER_USER, Config.GEOSERVER_PWD)
    headers = {
        "Content-Type": "application/json"
    }
    data = {"seedRequest": {
        "name": f"skolkovo_layers:{name}",
        "gridSetId": "EPSG:900913",
        "zoomStart": 0,
        "zoomStop": 30,
        "format": "image/png8",
        "type": "truncate"
    }}
    response = requests.post(
        url,
        headers=headers,
        data=data, 
        auth=HTTPBasicAuth(Config.GEOSERVER_USER, Config.GEOSERVER_PWD)
    )
    # Проверка ответа
    if response.status_code == 200:
        return {'status': 'ok'}
    else:
        logger.info(f'cache not cleared for layer {name}')


def upload_style_to_geoserver(layer_name: str, xml_str: str = None, style_name: str = None, delete_father:bool=True):
    """Загружает стиль на геосервер
    Args:
        path (str): Если указан - xml string стиля
        style_name (str): Если указан - имя стиля
    """
    style_path = f"{Config.UPLOAD_FOLDER}/sld/{layer_name}.sld"

    if xml_str is None and os.path.exists(style_path):
        with open(style_path, 'r') as sld_file:
            xml_str = sld_file.read().encode('utf-8')
    if xml_str is not None:
        if type(xml_str) == bytes:
            xml_str = xml_str.decode('utf-8')
        xml_str = convert_svg_to_css(xml_str)
    #если есть предыдущий стиль - удаляем. Это опциональный параметр
    if delete_father:
        try:
            geo.delete_style(style_name=layer_name, workspace=Config.GEOSERVER_WORKSPACE)
        except GeoserverException:
            pass
        except Exception as e:
            raise e
    if xml_str is None or xml_str == '':
        return
    geo.upload_style(path=xml_str.encode('utf-8'), name=style_name or layer_name, workspace=Config.GEOSERVER_WORKSPACE)
    geo.publish_style(layer_name=layer_name, style_name=layer_name, workspace=Config.GEOSERVER_WORKSPACE)


def delete_geoserver_style(style_name: str):
    try:
        result = geo.delete_layer(style_name, workspace=Config.GEOSERVER_WORKSPACE)
        geo.delete_style(style_name=style_name, workspace=Config.GEOSERVER_WORKSPACE)
    except GeoserverException as e:
        result = {"status": "bad", "error": "failed to delete layer from geoserver"}
    return result


def build_sld(style_dict: Dict[str, Any], layer_name: str, style_name: str = "autogenerated") -> str:
    """
    Преобразует твой словарь стиля в SLD 1.0.0 (как строку XML).
    Поддержка:
      - singleSymbol
      - categorizedSymbol (category rules с attribute/value/label; value=null → PropertyIsNull)
      - graduatedSymbol (range rules с lower/upper)
      - geometry: polygon|line|point (влияет на Symbolizer)
    """
    # корневой SLD
    sld = Element(f"{{{NS_SLD}}}StyledLayerDescriptor", {
        "version": "1.0.0",
        "xmlns": NS_SLD,
        "xmlns:ogc": NS_OGC,
        "xmlns:gml": NS_GML
    })
    named = SubElement(sld, f"{{{NS_SLD}}}NamedLayer")
    lname = SubElement(named, f"{{{NS_SLD}}}Name"); lname.text = layer_name

    ustyle = SubElement(named, f"{{{NS_SLD}}}UserStyle")
    sname = SubElement(ustyle, f"{{{NS_SLD}}}Name"); sname.text = style_name
    s_title = SubElement(ustyle, f"{{{NS_SLD}}}Title"); s_title.text = f"{style_name} for {layer_name}"

    fts = SubElement(ustyle, f"{{{NS_SLD}}}FeatureTypeStyle")

    rt = style_dict.get("renderer_type")
    rules = style_dict.get("rules") or []

    if rt == "singleSymbol":
        st = rules[0]["style"] if rules and "style" in rules[0] else {}
        _rule_with_filter(fts, "Все объекты", None, st.get("geometry", "polygon"), st)
        return _pretty_xml(sld)

    if rt == "categorizedSymbol":
        # вытащим имя атрибута из первого встречного правила
        attr = None
        for r in rules:
            if r.get("attribute"):
                attr = r["attribute"]
                break

        for r in rules:
            if r.get("type") != "category":
                continue
            val = r.get("value")
            label = r.get("label") or ("" if val is None else str(val))
            st = r.get("style") or {}
            if attr:
                if val is None or val == "":
                    filt = _filter_null(attr)
                else:
                    filt = _filter_eq(attr, val)
            else:
                filt = None  # если не прислали attribute, то правило без фильтра (редкий кейс)
            _rule_with_filter(fts, label, filt, st.get("geometry", "polygon"), st)

        return _pretty_xml(sld)

    if rt == "graduatedSymbol":
        # нижняя/верхняя границы + один attribute на все
        attr = None
        for r in rules:
            if r.get("attribute"):
                attr = r["attribute"]
                break
        for r in rules:
            if r.get("type") != "range":
                continue
            lower = float(r.get("lower"))
            upper = float(r.get("upper"))
            label = r.get("label") or f"{lower} – {upper}"
            st = r.get("style") or {}
            filt = _filter_between(attr, lower, upper) if attr else None
            _rule_with_filter(fts, label, filt, st.get("geometry", "polygon"), st)

        return _pretty_xml(sld)

    # неизвестный renderer → один дефолтный полигон
    _rule_with_filter(fts, "Все объекты", None, "polygon", {})
    return _pretty_xml(sld)


def convert_svg_to_css(sld_content: str):
    # Replace `se:SvgParameter` with `CssParameter`
    sld_content = re.sub(r"<se:SvgParameter", "<CssParameter", sld_content)
    sld_content = re.sub(r"</se:SvgParameter>", "</CssParameter>", sld_content)
    return sld_content


def _rgba_to_hex_opacity(rgba: str) -> Tuple[str, str]:
    """
    'rgba(226,215,250,1.000)' -> ('#E2D7FA', '1.0')
    'rgba(35,35,35,1.000)'   -> ('#232323', '1.0')
    Если передан #hex или rgb(), пытаемся разобрать; иначе возвращаем как есть + '1.0'
    """
    if not rgba:
        return ("#000000", "1.0")
    rgba = rgba.strip()
    m = re.match(r'rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([\d.]+)\s*\)', rgba, re.I)
    if m:
        r, g, b, a = map(str, m.groups())
        return (f"#{int(r):02X}{int(g):02X}{int(b):02X}", str(float(a)))
    m2 = re.match(r'rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)', rgba, re.I)
    if m2:
        r, g, b = map(int, m2.groups())
        return (f"#{r:02X}{g:02X}{b:02X}", "1.0")
    if rgba.startswith("#") and (len(rgba) in (4, 7)):
        return (rgba, "1.0")
    # fallback
    return (rgba, "1.0")

def _width_from_style(stroke: Dict[str, Any]) -> float:
    if not stroke:
        return 1.0
    if "width_px" in stroke:
        return float(stroke["width_px"])
    if "width" in stroke:
        return float(stroke["width"])
    return 1.0

def _dasharray_from_line_style(style_int: Optional[int]) -> Optional[str]:
    """
    Qt-like: 1=SolidLine, 2=DashLine, 3=DotLine, 4=DashDotLine, 5=DashDotDotLine
    Возвращаем строку для <CssParameter name="stroke-dasharray">.
    """
    if style_int is None:
        return None
    return {
        1: None,
        2: "6 6",
        3: "2 6",
        4: "6 6 2 6",
        5: "6 6 2 6 2 6"
    }.get(int(style_int), None)

def _pretty_xml(elem: Element) -> str:
    rough = tostring(elem, encoding="utf-8")
    return minidom.parseString(rough).toprettyxml(indent="  ", encoding="utf-8").decode("utf-8")

def _css_param(parent: Element, name: str, value: str):
    p = SubElement(parent, f"{{{NS_SLD}}}CssParameter", {"name": name})
    p.text = value
    return p

def _polygon_symbolizer(parent: Element, style: Dict[str, Any]):
    poly = SubElement(parent, f"{{{NS_SLD}}}PolygonSymbolizer")
    fill = style.get("fill", {})
    stroke = style.get("stroke", {})
    opacity = str(style.get("opacity", "")) or None

    # Fill
    if fill:
        fill_el = SubElement(poly, f"{{{NS_SLD}}}Fill")
        color_hex, alpha = _rgba_to_hex_opacity(fill.get("color", "rgba(158,158,158,0.25)"))
        _css_param(fill_el, "fill", color_hex)
        _css_param(fill_el, "fill-opacity", opacity or alpha)

    # Stroke
    if stroke:
        stroke_el = SubElement(poly, f"{{{NS_SLD}}}Stroke")
        color_hex, alpha = _rgba_to_hex_opacity(stroke.get("color", "rgba(97,97,97,0.9)"))
        _css_param(stroke_el, "stroke", color_hex)
        _css_param(stroke_el, "stroke-width", str(_width_from_style(stroke)))
        dash = _dasharray_from_line_style(stroke.get("line_style"))
        if dash:
            _css_param(stroke_el, "stroke-dasharray", dash)
        # прозрачноcть для stroke — если явно задана opacity в корне стиля — используем её, иначе alpha из rgba
        _css_param(stroke_el, "stroke-opacity", opacity or alpha)

def _line_symbolizer(parent: Element, style: Dict[str, Any]):
    line = SubElement(parent, f"{{{NS_SLD}}}LineSymbolizer")
    stroke = style.get("stroke", {}) or {}
    stroke_el = SubElement(line, f"{{{NS_SLD}}}Stroke")
    color_hex, alpha = _rgba_to_hex_opacity(stroke.get("color", "rgba(96,125,139,1)"))
    _css_param(stroke_el, "stroke", color_hex)
    _css_param(stroke_el, "stroke-width", str(_width_from_style(stroke)))
    dash = _dasharray_from_line_style(stroke.get("line_style"))
    if dash:
        _css_param(stroke_el, "stroke-dasharray", dash)
    _css_param(stroke_el, "stroke-opacity", alpha)

def _point_symbolizer(parent: Element, style: Dict[str, Any]):
    """
    Рисуем простой круг через WellKnownName=circle.
    Если в словаре есть markerSize/radius/markerFill/markerStroke — учитываем.
    """
    pt = SubElement(parent, f"{{{NS_SLD}}}PointSymbolizer")
    graphic = SubElement(pt, f"{{{NS_SLD}}}Graphic")
    mark = SubElement(graphic, f"{{{NS_SLD}}}Mark")
    name = SubElement(mark, f"{{{NS_SLD}}}WellKnownName"); name.text = "circle"

    # fill
    fill_in = style.get("markerFill") or style.get("fill", {})
    if fill_in:
        fill_el = SubElement(mark, f"{{{NS_SLD}}}Fill")
        color_hex, alpha = _rgba_to_hex_opacity(fill_in.get("color", "rgba(33,150,243,0.6)"))
        _css_param(fill_el, "fill", color_hex)
        _css_param(fill_el, "fill-opacity", alpha)

    # stroke
    stroke_in = style.get("markerStroke") or style.get("stroke", {})
    if stroke_in:
        stroke_el = SubElement(mark, f"{{{NS_SLD}}}Stroke")
        color_hex, alpha = _rgba_to_hex_opacity(stroke_in.get("color", "rgba(255,255,255,0.9)"))
        _css_param(stroke_el, "stroke", color_hex)
        _css_param(stroke_el, "stroke-width", str(_width_from_style(stroke_in)))
        dash = _dasharray_from_line_style(stroke_in.get("line_style"))
        if dash:
            _css_param(stroke_el, "stroke-dasharray", dash)
        _css_param(stroke_el, "stroke-opacity", alpha)

    # size
    size = style.get("markerSize") or style.get("radius") or 5
    size_el = SubElement(graphic, f"{{{NS_SLD}}}Size"); size_el.text = str(size)

def _symbolizer_by_geom(parent: Element, geom: str, style: Dict[str, Any]):
    g = (geom or "polygon").lower()
    if "point" in g:
        _point_symbolizer(parent, style)
    elif "line" in g:
        _line_symbolizer(parent, style)
    else:
        _polygon_symbolizer(parent, style)

def _rule_with_filter(parent: Element, label: str, filter_el: Optional[Element], geom: str, style: Dict[str, Any]):
    rule = SubElement(parent, f"{{{NS_SLD}}}Rule")
    title = SubElement(rule, f"{{{NS_SLD}}}Title"); title.text = label
    if filter_el is not None:
        rule.append(filter_el)
    _symbolizer_by_geom(rule, style.get("geometry", "polygon"), style)

def _filter_eq(attribute: str, value: Any) -> Element:
    f = Element(f"{{{NS_OGC}}}Filter")
    comp = SubElement(f, f"{{{NS_OGC}}}PropertyIsEqualTo")
    prop = SubElement(comp, f"{{{NS_OGC}}}PropertyName"); prop.text = attribute
    lit = SubElement(comp, f"{{{NS_OGC}}}Literal"); lit.text = "" if value is None else str(value)
    return f

def _filter_null(attribute: str) -> Element:
    f = Element(f"{{{NS_OGC}}}Filter")
    isnull = SubElement(f, f"{{{NS_OGC}}}PropertyIsNull")
    prop = SubElement(isnull, f"{{{NS_OGC}}}PropertyName"); prop.text = attribute
    return f

def _filter_between(attribute: str, lower: float, upper: float) -> Element:
    f = Element(f"{{{NS_OGC}}}Filter")
    between = SubElement(f, f"{{{NS_OGC}}}PropertyIsBetween")
    prop = SubElement(between, f"{{{NS_OGC}}}PropertyName"); prop.text = attribute
    lowerb = SubElement(between, f"{{{NS_OGC}}}LowerBoundary")
    SubElement(lowerb, f"{{{NS_OGC}}}Literal").text = str(lower)
    upperb = SubElement(between, f"{{{NS_OGC}}}UpperBoundary")
    SubElement(upperb, f"{{{NS_OGC}}}Literal").text = str(upper)